### ISSUE TITLE
Not Able to change Icon color?

### ISSUE THREAD

**Issue by WANTEDJAAT** [DvdGiessen/microphone-mute-indicator#3]
Hi,

Is there any way to change the icon color.?

Actually I keep my Notification area totally white, so your white icon is not visible.

Thanks

**Comment by DvdGiessen** [comment]
Hm, I hadn't considered the light theme. We use the built-in white icon from Windows itself (it's loaded [here](https://github.com/DvdGiessen/microphone-mute-indicator/blob/master/src/main.rs#L358-L372)), we can probably add a function that checks the current Windows taskbar color and chooses the appropriate icon.

> Actually I keep my Notification area totally white

To clarify, which setting(s) do you use in Windows to do this? So I can test it and check that any fix I make actually works. :)

**Comment by WANTEDJAAT** [comment]
In Windows Settings - Go to: Personalization > Colors

Turn Off these Both Options Below:
_Transparency Effects_
_Show Accent Color on title bars & windows borders_
& Keep Windows in Light Mode 

This way You can Keep your taskbar white in any situation. 

Now as your icon is Totally White (Screenshot Attached.), We can't see it on that clearly.
![Screenshot](https://github.com/DvdGiessen/microphone-mute-indicator/assets/16552096/1912a8be-7c82-409d-baac-1dcba50d130c)

_
I am Using Windows 11 BTW

_
One More thing... your app is also unrecognized app

 _Windows Defender detects Microsoft Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk._
 
 Please Look into that also
 
 Thanks

**Comment by DvdGiessen** [comment]
I've implemented an inverted icon color in [v0.2.2](https://github.com/DvdGiessen/microphone-mute-indicator/releases/tag/v0.2.2) which works well with a light theme taskbar. Thanks for the input!

**Comment by guinaicha** [comment]
Sorry if this is wrong to comment on a closed issue, but instead of making a new one thought I'd ask here first.

Is v0.2.2 supposed to choose the icon color based on taskbar color? Because I'm using a black taskbar and I still get a black icon. Using v0.2.1 I get the white icon.

**Comment by DvdGiessen** [comment]
v0.2.2 looks at the configured Windows theme (dark or light) to determine whether it should show a light or light taskbar icon (see the code [here](https://github.com/DvdGiessen/microphone-mute-indicator/blob/f55b7591f6c880e5c4df8dd7df2ea37ca8971f5b/src/main.rs#L507-L526)).

@guinaicha Are you perhaps using a black taskbar while using the light theme in WIndows?

**Comment by guinaicha** [comment]
Yes that was it, thank you. Specifically it's the "Choose your default app mode" in the Settings. Changing app mode to dark does change tray icon.

![colors](https://github.com/DvdGiessen/microphone-mute-indicator/assets/154325285/e100945c-21b7-4324-918a-75f4895fc488)

But seeing new issue you created, I do hope you end up supporting both those options.
