### ISSUE TITLE
Hotkey support

### ISSUE THREAD

**Issue by The-Mole-UK** [DvdGiessen/microphone-mute-indicator#5]
- I have one request.
- Please could you add a command to control the mic on/off status?  Ie rather than using the mouse, can assign a key for speed.  Ideally want something quick, like I press CTRL M.  Need a key that is quick to access, but does not prevent something else.
- Thank you.  I sometimes stumble to get my mouse there quick enough when on a call.   Ideally like one button near bottom.  Maybe the NUM ./DEL? or INSERT? or even better, user defined...

**Comment by DvdGiessen** [comment]
Glad to hear you like the program!

Hotkey support might be a useful feature indeed, though I'm not sure how easy it is to implement a global hotkey in Windows (and which edgecases would need to be handled for that to work correctly on all systems).

Also ideally I'd limit the user interface to just the systray (to not expand the scope of this program too much by adding a UI for settings), so perhaps a settings sub-menu with a user-friendly way to configure the desired hotkey.

Relates to #2 which also requires integration with the keyboard.

**Comment by The-Mole-UK** [comment]
[Microphone Mute Indicator 0.2.2 (x86).zip](https://github.com/DvdGiessen/microphone-mute-indicator/files/13910186/Microphone.Mute.Indicator.0.2.2.x86.zip)
This is a rough solution (and shows what I was thinking).  I've used Pause, Page Up, Page Down and Num Enter.
Now I can mute and unmute quick and see what I am doing...   Hopefully can use to implement a better solution?*
*Not a programmer! :(

**Comment by The-Mole-UK** [comment]
[Microphone Mute Indicator 0.2.2 (x86).zip](https://github.com/DvdGiessen/microphone-mute-indicator/files/13981681/Microphone.Mute.Indicator.0.2.2.x86.zip) / https://www.autohotkey.com/
- This is my current build using AutoHotkey 1.1.37.01 to make an exe.
- Allows me to control the mic status of Microphone Mute Indicator by pressing keys on the left and right of keyboard.
I work from home and do not want to say anything dumb that can be recorded.
- Means can control with left hand and keep right on the mouse, if doing my own thing on screen 2.
- Updated 18-01-2024.  / Did not write the tool to tell you the ID.

**Comment by The-Mole-UK** [comment]
Demo...
[Video.zip](https://github.com/DvdGiessen/microphone-mute-indicator/files/13981843/Video.zip)

**Comment by guinaicha** [comment]
How about allowing the program to mute/unmute via cmd? If that is supported then we can instead just make a shortcut to the exe with relevant arguments, and then assign keyboard shortcut to it.

https://www.tenforums.com/tutorials/93130-how-assign-keyboard-shortcut-shortcuts-windows-10-a.html

At the moment running the exe in cmd just launches a second instance of it.

**Comment by DvdGiessen** [comment]
An option to mute/unmute via the command line has been added in [the just released v0.3.0](https://github.com/DvdGiessen/microphone-mute-indicator/releases/tag/v0.3.0). See the README for details on how to use it.

**Comment by The-Mole-UK** [comment]
I have an ahk program I use to redefine the keyboard when working, so some keys do not work.  Excluding [TAB].
Is it possible that when MMI is loaded and in the Taskbar, [TAB] rotates Mute/Unmute please?
Issue with command line method, is that the program will load several times in the Taskbar with the status changing each time.
I want to load 0.31 once to the Taskbar, and then, when I press [TAB] it does the same function and status as a [Left mouse] click.

Thanks :)

**Comment by DvdGiessen** [comment]
> Issue with command line method, is that the program will load several times in the Taskbar with the status changing each time.

Actually, you can set it to quit after performing the mute toggle by adding the `--action-exit` parameter. For example:

```
microphone-mute-indicator.exe --action-toggle-mute --action-exit
```

This will change the microphone muted state, and then exit immediately (thus not leaving any extra icons in the taskbar).

I'm closing this issue as out of scope for this project, and hoping that the command line option makes it easy enough to implement it using another tool that handles the hotkeys. :)
