### ISSUE TITLE
Start with windows

### ISSUE THREAD

**Issue by limweidavid** [DvdGiessen/microphone-mute-indicator#9]
Could you add start with windows option?

**Comment by DvdGiessen** [comment]
You can place the `microphone-mute-indicator.exe` file in your Startup directory (`C:\Users\<USERNAME>\AppData\Microsoft\Windows\Start Menu\Programs\Startup`, or press Win + R and type `shell:startup` to go there) to automatically start it when you log in to your computer.

**Comment by limweidavid** [comment]
Cool. Thanks.
